### Copyright 2022 Omar Suleiman

steps:

### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/omar-devops/translate-app-img:${SHORT_SHA}', './cloud/python' ]

## Push / Publish
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/omar-devops/translate-app-img:${SHORT_SHA}']

### Deploy
  - id: 'pre-deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          sed -i 's|gcr.io/omar-devops/translate-app-img:.*|gcr.io/omar-devops/translate-app-img:${SHORT_SHA}|' ./terraform/gcp.tf


# Run terraform
  - id: 'deploy'
    name: 'gcr.io/omar-devops/terraform'
    entrypoint: 'bash'
    dir: 'terraform'
    args:
      - '-c'
      - |
          yes | terraform apply
    # entrypoint: 'terraform' 
    # args: ['yes','|','apply']
             

# ### Build

#   - id: 'build'
#     name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'bash'
#     args: 
#       - '-c'
#       - |
#           docker build -t gcr.io/omar-devops/translate-app-img ./cloud/python


# ### Test


# ### Publish
#   - id: 'publish'
#     name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'bash'
#     args: 
#       - '-c'
#       - |
#           docker push gcr.io/omar-devops/translate-app-img



### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
